Repository ConducereIT/arena-electronistilor, pull requests merged in 2023-11, with the labels that each got.

#2 Init
  .gitignore
  client/.gitignore
  client/README.md
  client/package-lock.json
  client/package.json
  client/public/favicon.ico
  client/public/index.html
  client/public/logo192.png
  client/public/logo512.png
  client/public/manifest.json
  client/public/robots.txt
  client/src/App.css
  client/src/App.test.tsx
  client/src/App.tsx
  client/src/index.css
  client/src/index.tsx
  client/src/logo.svg
  client/src/react-app-env.d.ts
  client/src/reportWebVitals.ts
  client/src/setupTests.ts
  client/tsconfig.json
  genezio.yaml
  server/helloWorld.ts
  server/package-lock.json
  server/package.json
  server/tsconfig.json
Labels: READY TO MERGE

#10 Added Admin/AddMainQuestion
  client/src/components/AdminAddQuestionMainRound/AddQuestion.component.tsx
  client/src/views/AdminAddQuestionMainRound.view.tsx
Labels: READY TO MERGE, Check Work

#6 Get LeaderBoard error
  .vscode/tasks.json
  client/src/sdk/models/typeUser.ts
  client/src/sdk/user.sdk.ts
  server/Game.ts
  server/models/typeGame.ts
  server/models/typeUser.ts
  server/prisma/schema.prisma
Labels: bug, help wanted
